resources:
  Dbp\Relay\DispatchBundle\Entity\Group:
    types: ['https://schema.org/Organization']
    shortName: 'DispatchGroup'
    normalizationContext:
      groups: ['DispatchGroup:output']

    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\GroupProvider
        uriTemplate: '/dispatch/groups/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\GroupProvider
        uriTemplate: '/dispatch/groups'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      street:
        iri: 'https://schema.org/streetAddress'
      locality:
        iri: 'https://schema.org/addressLocality'
      postalCode:
        iri: 'https://schema.org/postalCode'
      country:
        iri: 'https://schema.org/addressCountry'
      accessRights:

  Dbp\Relay\DispatchBundle\Entity\DeliveryStatusChange:
    types: ['https://schema.org/Status']
    shortName: 'DispatchDeliveryStatusChange'
    normalizationContext:
      groups: ['DispatchDeliveryStatusChange:output']

    operations:
      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeProvider
        uriTemplate: '/dispatch/request-status-changes/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeProvider
        uriTemplate: '/dispatch/request-status-changes'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      dateCreated:
        iri: 'https://schema.org/dateCreated'
      requestRecipient:
      dispatchRequestRecipientIdentifier:
        iri: 'https://schema.org/identifier'
      statusType:
        iri: 'https://schema.org/statusType'
      dispatchStatus:
        iri: 'https://schema.org/statusType'
      description:
        iri: 'https://schema.org/description'
      fileFormat:
        iri: 'https://schema.org/fileFormat'
      fileContentUrl:
        iri: 'http://schema.org/contentUrl'

  Dbp\Relay\DispatchBundle\Entity\RequestRecipient:
    types: ['https://schema.org/Person']
    shortName: 'DispatchRequestRecipient'
    normalizationContext:
      groups: ['DispatchRequestRecipient:output']
    denormalizationContext:
      groups: ['DispatchRequestRecipient:input']

    operations:

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProvider
        uriTemplate: '/dispatch/request-recipients'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProcessor
        uriTemplate: '/dispatch/request-recipients'
        openapiContext:
          tags: ["Dispatch"]
          requestBody:
            content:
              application/json:
                schema:
                  type: "object"
                  example:
                    dispatchRequestIdentifier: "4d553985-d44f-404f-acf3-cd0eac7ae9c2"
                    givenName: "Max"
                    familyName: "Mustermann"
                    addressCountry: "AT"
                    postalCode: "8010"
                    addressLocality: "Graz"
                    streetAddress: "Am Grund"
                    buildingNumber: "1"
                    birthDate: "1980-01-01"

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProvider
        uriTemplate: '/dispatch/request-recipients/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Delete:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProvider
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProcessor
        uriTemplate: '/dispatch/request-recipients/{identifier}'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      dateCreated:
        iri: 'https://schema.org/dateCreated'
      request:
      dispatchRequestIdentifier:
        iri: 'https://schema.org/identifier'
      givenName:
        iri: 'https://schema.org/givenName'
      familyName:
        iri: 'https://schema.org/familyName'
      addressCountry:
        iri: 'https://schema.org/addressCountry'
      postalCode:
        iri: 'https://schema.org/postalCode'
      addressLocality:
        iri: 'https://schema.org/addressLocality'
      streetAddress:
        iri: 'https://schema.org/streetAddress'
      buildingNumber:
      birthDate:
        iri: 'http://schema.org/birthDate'
      dualDeliveryID:
      appDeliveryID:
      deliveryEndDate:
        iri: 'https://schema.org/endDate'
      personIdentifier:
        iri: 'https://schema.org/identifier'
      postalDeliverable:
      electronicallyDeliverable:
      lastStatusChange:
      statusChanges:

  Dbp\Relay\DispatchBundle\Entity\PreAddressingRequest:
    types: ['https://schema.org/Action']
    shortName: 'DispatchPreAddressingRequest'
    normalizationContext:
      groups: ['DispatchPreAddressingRequest:output']
    denormalizationContext:
      groups: ["DispatchPreAddressingRequest:input"]

    operations:
      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\PreAddressingRequestProvider
        uriTemplate: '/dispatch/pre-addressing-requests/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\PreAddressingRequestProvider
        uriTemplate: '/dispatch/pre-addressing-requests'
        openapiContext:
          tags: ['Dispatch']

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\PreAddressingRequestProcessor
        uriTemplate: '/dispatch/pre-addressing-requests'
        openapiContext:
          tags: ['Dispatch']
          requestBody:
            content:
              application/json:
                schema:
                  type: "object"
                  example:
                    givenName: "Max"
                    familyName: "Mustermann"
                    birthDate: "1980-01-01"

    properties:
      identifier:
        identifier: true
      givenName:
        iri: 'https://schema.org/givenName'
      familyName:
        iri: 'https://schema.org/familyName'
      birthDate:
        iri: 'http://schema.org/birthDate'