resources:
  Dbp\Relay\DispatchBundle\Entity\Group:
    types: ['https://schema.org/Organization']
    shortName: 'DispatchGroup'
    normalizationContext:
      groups: ['DispatchGroup:output']

    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\GroupProvider
        uriTemplate: '/dispatch/groups/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\GroupProvider
        uriTemplate: '/dispatch/groups'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      street:
        iri: 'https://schema.org/streetAddress'
      locality:
        iri: 'https://schema.org/addressLocality'
      postalCode:
        iri: 'https://schema.org/postalCode'
      country:
        iri: 'https://schema.org/addressCountry'
      accessRights:

  Dbp\Relay\DispatchBundle\Entity\DeliveryStatusChange:
    types: ['https://schema.org/Status']
    shortName: 'DispatchDeliveryStatusChange'
    normalizationContext:
      groups: ['DispatchDeliveryStatusChange:output']

    operations:
      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeProvider
        uriTemplate: '/dispatch/request-status-changes/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeProvider
        uriTemplate: '/dispatch/request-status-changes'
        openapiContext:
          tags: ['Dispatch']

      ApiPlatform\Metadata\Delete:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeFileProcessor
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeFileProvider
        uriTemplate: '/dispatch/request-status-changes/{identifier}/file'
        openapiContext:
          summary: "Removes the DispatchDeliveryStatusChange file resource."
          tags: ['Dispatch']

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        controller: Dbp\Relay\DispatchBundle\ApiPlatform\UpdateDeliveryStatusChangeFileAction
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeFileProvider
        uriTemplate: '/dispatch/request-status-changes/{identifier}/file'
        method: 'POST'
        deserialize: false
        inputFormats:
          multipart: "multipart/form-data"
        openapiContext:
          tags: ["Dispatch"]
          responses:
            415:
              description: "Unsupported Media Type - Only PDF files can be added!"
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: "object"
                  required: ["file", "dispatchRequestIdentifier", "fileUploaderIdentifier"]
                  properties:
                    dispatchRequestIdentifier:
                      description: "ID of the request"
                      type: "string"
                      example: "4d553985-d44f-404f-acf3-cd0eac7ae9c2"
                    file:
                      type: "string"
                      format: "binary"
                    fileUploaderIdentifier:
                      description: "User ID of the file uploader"
                      type: "string"
                      example: "F957F2400C941B72"

    properties:
      identifier:
        identifier: true
      dateCreated:
        iri: 'https://schema.org/dateCreated'
      requestRecipient:
      dispatchRequestRecipientIdentifier:
        iri: 'https://schema.org/identifier'
      statusType:
        iri: 'https://schema.org/statusType'
      dispatchStatus:
        iri: 'https://schema.org/statusType'
      description:
        iri: 'https://schema.org/description'
      fileFormat:
        iri: 'https://schema.org/fileFormat'
      fileContentUrl:
        iri: 'http://schema.org/contentUrl'

  Dbp\Relay\DispatchBundle\Entity\RequestRecipient:
    types: ['https://schema.org/Person']
    shortName: 'DispatchRequestRecipient'
    normalizationContext:
      groups: ['DispatchRequestRecipient:output']
    denormalizationContext:
      groups: ['DispatchRequestRecipient:input']

    operations:

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProvider
        uriTemplate: '/dispatch/request-recipients'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProcessor
        uriTemplate: '/dispatch/request-recipients'
        openapiContext:
          tags: ["Dispatch"]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  example:
                    dispatchRequestIdentifier: "4d553985-d44f-404f-acf3-cd0eac7ae9c2"
                    givenName: "Max"
                    familyName: "Mustermann"
                    addressCountry: "AT"
                    postalCode: "8010"
                    addressLocality: "Graz"
                    streetAddress: "Am Grund"
                    buildingNumber: "1"
                    birthDate: "1980-01-01"

      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProvider
        uriTemplate: '/dispatch/request-recipients/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Delete:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProvider
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestRecipientProcessor
        uriTemplate: '/dispatch/request-recipients/{identifier}'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      dateCreated:
        iri: 'https://schema.org/dateCreated'
      request:
      dispatchRequestIdentifier:
        iri: 'https://schema.org/identifier'
      givenName:
        iri: 'https://schema.org/givenName'
      familyName:
        iri: 'https://schema.org/familyName'
      addressCountry:
        iri: 'https://schema.org/addressCountry'
      postalCode:
        iri: 'https://schema.org/postalCode'
      addressLocality:
        iri: 'https://schema.org/addressLocality'
      streetAddress:
        iri: 'https://schema.org/streetAddress'
      buildingNumber:
      birthDate:
        iri: 'http://schema.org/birthDate'
      dualDeliveryID:
      appDeliveryID:
      deliveryEndDate:
        iri: 'https://schema.org/endDate'
      personIdentifier:
        iri: 'https://schema.org/identifier'
      postalDeliverable:
      electronicallyDeliverable:
      lastStatusChange:
      statusChanges:

  Dbp\Relay\DispatchBundle\Entity\PreAddressingRequest:
    types: ['https://schema.org/Action']
    shortName: 'DispatchPreAddressingRequest'
    normalizationContext:
      groups: ['DispatchPreAddressingRequest:output']
    denormalizationContext:
      groups: ["DispatchPreAddressingRequest:input"]

    operations:
      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\PreAddressingRequestProvider
        uriTemplate: '/dispatch/pre-addressing-requests/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\PreAddressingRequestProvider
        uriTemplate: '/dispatch/pre-addressing-requests'
        openapiContext:
          tags: ['Dispatch']

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\PreAddressingRequestProcessor
        uriTemplate: '/dispatch/pre-addressing-requests'
        openapiContext:
          tags: ['Dispatch']
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  example:
                    givenName: "Max"
                    familyName: "Mustermann"
                    birthDate: "1980-01-01"

    properties:
      identifier:
        identifier: true
      givenName:
        iri: 'https://schema.org/givenName'
      familyName:
        iri: 'https://schema.org/familyName'
      birthDate:
        iri: 'http://schema.org/birthDate'

  Dbp\Relay\DispatchBundle\Entity\RequestFile:
    types: ['https://schema.org/DigitalDocument']
    shortName: 'DispatchRequestFile'
    normalizationContext:
      groups: ['DispatchRequestFile:output', 'DispatchRequest:output']
    denormalizationContext:
      groups: ["DispatchRequestFile:input"]

    operations:
      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestFileProvider
        uriTemplate: '/dispatch/request-files/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Delete:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestFileProvider
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestFileProcessor
        uriTemplate: '/dispatch/request-files/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        controller: Dbp\Relay\DispatchBundle\ApiPlatform\CreateRequestFileAction
        uriTemplate: "/dispatch/request-files"
        method: 'POST'
        deserialize: false
        inputFormats:
          multipart: "multipart/form-data"
        openapiContext:
          tags: ["Dispatch"]
          responses:
            415:
              description: "Unsupported Media Type - Only PDF files can be added!"
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: "object"
                  required: ["file", "dispatchRequestIdentifier"]
                  properties:
                    dispatchRequestIdentifier:
                      description: "ID of the request"
                      type: "string"
                      example: "4d553985-d44f-404f-acf3-cd0eac7ae9c2"
                    file:
                      type: "string"
                      format: "binary"

    properties:
      identifier:
        identifier: true
      dateCreated:
        iri: 'https://schema.org/dateCreated'
      request:
      dispatchRequestIdentifier:
        iri: "https://schema.org/identifier"
      name:
        iri: 'https://schema.org/name'
      contentUrl:
        iri: 'http://schema.org/contentUrl'
      fileFormat:
        iri: 'https://schema.org/fileFormat'
      contentSize:
        iri: 'https://schema.org/contentSize'

  Dbp\Relay\DispatchBundle\Entity\Request:
    types: ['https://schema.org/Action']
    shortName: 'DispatchRequest'
    normalizationContext:
      groups: ['DispatchRequest:output']
    denormalizationContext:
      groups: ["DispatchRequest:input"]

    operations:
      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestProvider
        uriTemplate: '/dispatch/requests/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Patch:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestProvider
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestProcessor
        uriTemplate: '/dispatch/requests/{identifier}'
        inputFormats:
          json: ['application/merge-patch+json']
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Delete:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestProvider
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestProcessor
        uriTemplate: '/dispatch/requests/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        processor: Dbp\Relay\DispatchBundle\ApiPlatform\RequestProcessor
        uriTemplate: "/dispatch/requests"
        openapiContext:
          tags: ["Dispatch"]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  example:
                    name: "Aussendung 42"
                    senderFullName: "Max Mustermann"
                    senderOrganizationName: "Studienservice TU Graz"
                    senderAddressCountry: "AT"
                    senderPostalCode: "8010"
                    senderAddressLocality: "Graz"
                    senderStreetAddress: "Am Grund"
                    senderBuildingNumber: "1"
                    groupId: "11072"
                    referenceNumber: "GZ-2023/01-13"

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\RequestProvider
        uriTemplate: '/dispatch/requests'
        openapiContext:
          tags: ['Dispatch']
          parameters:
            - name: "groupId"
              in: "query"
              description: 'The group ID for which to fetch requests'
              required: true
              type: "string"

      post_submit:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        class: ApiPlatform\Metadata\Post
        method: POST
        uriTemplate: "/dispatch/requests/{identifier}/submit"
        controller: Dbp\Relay\DispatchBundle\ApiPlatform\PostSubmitRequest
        read: false
        write: false
        deserialize: false
        validate: false
        openapiContext:
          summary: "Submits the request."
          tags: ["Dispatch"]
          parameters:
            - name: "identifier"
              in: "path"
              description: 'ID of the request'
              required: true
              type: "string"
              example: "4d553985-d44f-404f-acf3-cd0eac7ae9c2"
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  example: '{}'

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      dateCreated:
        iri: 'https://schema.org/dateCreated'
      personIdentifier:
        iri: 'https://schema.org/identifier'
      senderFullName:
        iri: 'https://schema.org/alternateName'
      senderOrganizationName:
        iri: 'https://schema.org/alternateName'
      dateSubmitted:
      senderAddressCountry:
        iri: 'https://schema.org/addressCountry'
      senderPostalCode:
        iri: 'https://schema.org/postalCode'
      senderAddressLocality:
        iri: 'https://schema.org/addressLocality'
      senderStreetAddress:
        iri: 'https://schema.org/streetAddress'
      senderBuildingNumber:
      groupId:
      referenceNumber: