resources:
  Dbp\Relay\DispatchBundle\Entity\Group:
    types: ['https://schema.org/Organization']
    shortName: 'DispatchGroup'
    normalizationContext:
      groups: ['DispatchGroup:output']

    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\GroupProvider
        uriTemplate: '/dispatch/groups/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\GroupProvider
        uriTemplate: '/dispatch/groups'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      street:
        iri: 'https://schema.org/streetAddress'
      locality:
        iri: 'https://schema.org/addressLocality'
      postalCode:
        iri: 'https://schema.org/postalCode'
      country:
        iri: 'https://schema.org/addressCountry'
      accessRights:

  Dbp\Relay\DispatchBundle\Entity\DeliveryStatusChange:
    types: ['https://schema.org/Status']
    shortName: 'DispatchDeliveryStatusChange'
    normalizationContext:
      groups: ['DispatchDeliveryStatusChange:output']

    operations:
      ApiPlatform\Metadata\Get:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeProvider
        uriTemplate: '/dispatch/request-status-changes/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        provider: Dbp\Relay\DispatchBundle\ApiPlatform\DeliveryStatusChangeProvider
        uriTemplate: '/dispatch/request-status-changes'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      dateCreated:
        iri: 'https://schema.org/dateCreated'
      requestRecipient:
      dispatchRequestRecipientIdentifier:
        iri: 'https://schema.org/identifier'
      statusType:
        iri: 'https://schema.org/statusType'
      dispatchStatus:
        iri: 'https://schema.org/statusType'
      description:
        iri: 'https://schema.org/description'
      fileFormat:
        iri: 'https://schema.org/fileFormat'
      fileContentUrl:
        iri: 'http://schema.org/contentUrl'
