resources:
  Dbp\Relay\DispatchBundle\Entity\Group:
    types: ['https://schema.org/Organization']
    shortName: 'DispatchGroup'
    normalizationContext:
      groups: ['DispatchGroup:output']
      jsonld_embed_context: true
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\DispatchBundle\DataProvider\GroupDataProvider
        uriTemplate: '/dispatch/groups/{identifier}'
        openapiContext:
          tags: ["Dispatch"]

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\DispatchBundle\DataProvider\GroupDataProvider
        uriTemplate: '/dispatch/groups'
        openapiContext:
          tags: ['Dispatch']

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      street:
        iri: 'https://schema.org/streetAddress'
      locality:
        iri: 'https://schema.org/addressLocality'
      postalCode:
        iri: 'https://schema.org/postalCode'
      country:
        iri: 'https://schema.org/addressCountry'
      accessRights:
