services:
  Dbp\Relay\DispatchBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Service\DispatchService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_dispatch_bundle_entity_manager'

  Dbp\Relay\DispatchBundle\Service\BlobService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Service\GroupService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Controller\:
    tags: ['controller.service_arguments']
    resource: '../../Controller'
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Authorization\EntityNormalizer:
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Authorization\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Service\DualDeliveryService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\MessageHandler\RequestSubmissionHandler:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['messenger.message_handler']

  Dbp\Relay\DispatchBundle\Cron\StatusCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true
