services:
  Dbp\Relay\DispatchBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\DispatchBundle\DataProvider\RequestCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true

  Dbp\Relay\DispatchBundle\DataProvider\RequestItemDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true

  Dbp\Relay\DispatchBundle\DataProvider\RequestRecipientItemDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true

  Dbp\Relay\DispatchBundle\Service\DispatchService:
    autowire: true
    autoconfigure: true
